# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directories: 
      - "/.github/mkdocs/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      mkdocs-pip-dependencies:
        patterns:
          - "/.github/mkdocs/*"
