# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "zensical"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    ignore:
      - dependency-name: "zensical"
        update-types:
          - "version-update:semver-patch"
    cooldown:
      include:
        - "zensical"
      default-days: 90

