name: github_image

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/github_image.yml'
      - '.github/docker/**/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/docker/**/**'
      - '!.github/workflows/**'
  schedule:
    - cron: '45 18 28 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}${{ github.event.pull_request.number && '-' }}${{ github.event.pull_request.number || '' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' && true || true }}


jobs:
  matrizifizieren:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    outputs:
      gitsha: ${{ steps.parse.outputs.gitsha }}
      images: ${{ steps.filter.outputs.changes }}

    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: filter
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            dl-packs:
              - '.github/workflows/${{ github.workflow }}.yml'
              - '.github/docker/dl-packs/**'
            firmware:
              - '.github/workflows/${{ github.workflow }}.yml'
              - '.github/docker/firmware/**'
            generate:
              - '.github/workflows/${{ github.workflow }}.yml'
              - '.github/docker/generate/**'

      - name: parse
        id: parse
        run: |
          echo "gitsha=\"${{ github.sha }}\"" >> $GITHUB_OUTPUT

      - name: vars
        id: vars
        run: |
          echo "################################################################"
          echo "IMAGES=${{ steps.filter.outputs.changes }}"
          echo "################################################################"
          echo "GITSHA=${{ steps.parse.outputs.gitsha }}"

  build:
    permissions:
      contents: read
      packages: write
    needs: matrizifizieren
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.matrizifizieren.outputs.images) }}
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner || github.actor }}/${{ matrix.image }}
      CONTEXT: ./.github/docker/${{ matrix.image }}

    steps:

      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ fromJson(needs.matrizifizieren.outputs.gitsha) }}

      - name: login
        if: github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest

      - name: docker
        uses: docker/build-push-action@v7
        with:
          context: ${{ env.CONTEXT }}
          push: ${{ github.repository == 'freetz-ng/freetz-ng' && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


