name: invoke_tests

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
 linux:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-18.04']
        env_vars:
          - ''
          # allow for some parallelity without GNU parallel, since it is not installed by default
          - 'BATS_NO_PARALLELIZE_ACROSS_FILES=1 BATS_NUMBER_OF_PARALLEL_JOBS=2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run test on OS ${{ matrix.os }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: |
          cd /test
          bash --version
          bash -c "time ${{ matrix.env_vars }} ./test_runner"

  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm install -g npm@6
      - run: npm cache clean --force
      - run: npm login --registry=https://registry.npmjs.org
      - run: npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}