#  author : sven zaugg
#    file : invoke_tests.yml
# purpose : github workflow for invoking freetz-ng test suite, i.e. /test/test_runner

name: invoke_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-latest']
        env_vars:
          # allow for some parallelity without GNU parallel, since it is not installed by default
          # BATS_NO_PARALLELIZE_ACROSS_FILES=1
          - 'BATS_NUMBER_OF_PARALLEL_JOBS=2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run test on OS ${{ matrix.os }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: |
          cd test
          bash --version
          bash -c "time ${{ matrix.env_vars }} ./test_runner"    