name: postcommit_diffs

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/postcommit_diffs.yml'
      - 'make/kernel/configs/generate.sh'
      - 'make/kernel/configs/avm/*'
      - 'make/kernel/configs/freetz/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng'

    steps:

      - name: dependencies-check
        run: |
          for cmd in git locales; do
            if apt list --installed 2>/dev/null | grep -q "^$cmd/"
            then
              echo "$cmd is installed"
            else
              echo "$cmd is NOT installed" && MISSING_PACKAGES="$MISSING_PACKAGES $cmd"
            fi
          done
          if [ -n "$MISSING_PACKAGES" ]; then
            echo "The following packages are missing: $MISSING_PACKAGES"
            echo "Installing missing packages..."
            sudo apt-get -qq update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install $MISSING_PACKAGES
          fi

      - name: locale
        run: sudo $SHELL -c "locale-gen en_US.utf8 && locale-gen de_DE.UTF-8 && update-locale"

      - name: clone
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          set-safe-directory: true
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          path: ${{ github.workspace }}
          fetch-depth: 0
          clean: false
          persist-credentials: true

      - name: generate
        run: |
          export LANG=en_US.utf8
          make/kernel/configs/generate.sh

      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git pull
          git add .
          git status
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git diff --cached --quiet && exit 0 || git commit -m "diffs: automatic update"
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME


